# Generated by Django 4.2.7 on 2023-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskCategory', '0002_remove_category_tasks'),
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='taskCategory.category'),
        ),
    ]
